In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
a={
    "names":["amazon","netflix","aha","tesco"],
     "values":["today","tomorrow","rajesh","maddi"]
}
df=pd.DataFrame(a)
obj=LabelEncoder()
df["names_n"]=obj.fit_transform(df["names"])
df["values_n"]=obj.fit_transform(df["values"])
df

names    values  names_n  values_n
0   amazon     today        1         2
1  netflix  tomorrow        2         3
2      aha    rajesh        0         1
3    tesco     maddi        3         0

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
a={
    "x":[10,20,30,40,50,60],
     "y":[100,200,300,400,500,600]
}
df=pd.DataFrame(a)
obj=MinMaxScaler(feature_range=(0,1))
df[["x","y"]]=obj.fit_transform(df[["x","y"]])
df

x    y
0  0.0  0.0
1  0.2  0.2
2  0.4  0.4
3  0.6  0.6
4  0.8  0.8
5  1.0  1.0

In [3]:
import pandas as pd
import numpy as np
a={
    "salary":[234,567,899,789],
     "values":[2,3,4,290],
      "wages":[234,678,999,678]
}
df=pd.DataFrame(a)
cond1=df["values"]<6
print(df[cond1])

   salary  values  wages
0     234       2    234
1     567       3    678
2     899       4    999


In [4]:
df["outliers"]=np.where(cond1,0,1)
df

salary  values  wages  outliers
0     234       2    234         0
1     567       3    678         0
2     899       4    999         0
3     789     290    678         1

In [5]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="mean")
x=df[["marks"]].values
df["marks"]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3   78.0      M    average
4   70.0      M       good
5   78.0    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [6]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="most_frequent")
x=df[["marks"]].values
df["marks"]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3   60.0      M    average
4   70.0      M       good
5   60.0    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [7]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
data=np.array([["blue"],["green"],["red"]])
obj=OrdinalEncoder()
result=obj.fit_transform(data)
result

array([[0.],
       [1.],
       [2.]])

In [8]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
a=[["coffee"],["badam"],["yellow"]]
obj=OrdinalEncoder()
result=obj.fit_transform(a)
result

array([[1.],
       [0.],
       [2.]])

In [9]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
data=asarray([["xerox"],["car"],["yellow"]])
obj=OrdinalEncoder()
result=obj.fit_transform(data)
result

array([[1.],
       [0.],
       [2.]])

In [10]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=([["tiger"],["peakok"],["elephant"]])
data=asarray(a)
obj=OneHotEncoder(sparse_output=False)
result=obj.fit_transform(data)
result

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [11]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
a=np.array([["money"],["cash"],["tiger"]])
obj=OneHotEncoder(sparse_output=False)
result=obj.fit_transform(a)
result

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [12]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=asarray([["ok"],["chintu"],["people"]])
obj=OneHotEncoder(sparse_output=False,drop="first")
result=obj.fit_transform(a)
result

array([[1., 0.],
       [0., 0.],
       [0., 1.]])

In [13]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan,np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="most_frequent")
x=df[["gender"]].values
df[["gender"]]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0      M       good
3    NaN      M    average
4   70.0      M       good
5    NaN      M   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [14]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
a={
    "names":["amazon","aha","netflix","tesco"],
     "values":["ok","rajesh","maddi","today"]
}
df=pd.DataFrame(a)
obj=LabelEncoder()
df["names_n"]=obj.fit_transform(df["names"])
df["values_n"]=obj.fit_transform(df["values"])
df

names  values  names_n  values_n
0   amazon      ok        1         1
1      aha  rajesh        0         2
2  netflix   maddi        2         0
3    tesco   today        3         3

In [15]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
a={
     "x":[10,20,30,40,50,60],
      "y":[100,200,300,400,500,600]
}
df=pd.DataFrame(a)
obj=MinMaxScaler(feature_range=(0,1))
df[["x","y"]]=obj.fit_transform(df[["x","y"]])
df

x    y
0  0.0  0.0
1  0.2  0.2
2  0.4  0.4
3  0.6  0.6
4  0.8  0.8
5  1.0  1.0

In [16]:
import pandas as pd
import numpy as np
a={
    "salees":[234,567,899,7899],
    "values":[2,3,4,200],
     "area":[987,786,897,899]
}
df=pd.DataFrame(a)
cond1=df["values"]<5
print(df[cond1])

   salees  values  area
0     234       2   987
1     567       3   786
2     899       4   897


In [17]:
df["outliers"]=np.where(cond1,True,False)
df

salees  values  area  outliers
0     234       2   987      True
1     567       3   786      True
2     899       4   897      True
3    7899     200   899     False

In [18]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="constant")
x=df[["marks"]].values
df["marks"]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3    0.0      M    average
4   70.0      M       good
5    0.0    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [19]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
a=asarray([["amazon"],["netflix"],["aha"]])
obj=OrdinalEncoder()
result=obj.fit_transform(a)
result

array([[1.],
       [2.],
       [0.]])

In [20]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=asarray([["tiger"],["elephant"],["horse"]])
obj=OneHotEncoder(sparse_output=False)
result=obj.fit_transform(a)
print(result)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [21]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
a={
    "names":["amazon","aha","netflix","tesco","asda"],
     "values":["rajesh","maddi","today","tomorrow","ok"]
}
df=pd.DataFrame(a)
obj=LabelEncoder()
df["names_n"]=obj.fit_transform(df["names"])
df["values_n"]=obj.fit_transform(df["values"])
df

names    values  names_n  values_n
0   amazon    rajesh        1         2
1      aha     maddi        0         0
2  netflix     today        3         3
3    tesco  tomorrow        4         4
4     asda        ok        2         1

In [22]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
a={
    "x":[10,20,30,40,50,60],
     "y":[100,200,300,400,500,600]
}
df=pd.DataFrame(a)
obj=MinMaxScaler(feature_range=(0,1))
df[["x","y"]]=obj.fit_transform(df[["x","y"]])
df

x    y
0  0.0  0.0
1  0.2  0.2
2  0.4  0.4
3  0.6  0.6
4  0.8  0.8
5  1.0  1.0

In [23]:
import pandas as pd
import numpy as np
a={
    "salary":[2345,6789,7899,9999],
    "values":[2,3,4,200],
     "rent":[8769,6789,5678,8999]
}
df=pd.DataFrame(a)
cond1=df["values"]<5



In [24]:
print(df[cond1])

   salary  values  rent
0    2345       2  8769
1    6789       3  6789
2    7899       4  5678


In [25]:
df["outliers"]=np.where(cond1,True,False)
df

salary  values  rent  outliers
0    2345       2  8769      True
1    6789       3  6789      True
2    7899       4  5678      True
3    9999     200  8999     False

In [26]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="mean")
x=df[["marks"]].values
df[["marks"]]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3   78.0      M    average
4   70.0      M       good
5   78.0    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [27]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="most_frequent")
x=df[["marks"]].values
df[["marks"]]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3   60.0      M    average
4   70.0      M       good
5   60.0    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [28]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
a=asarray([["amazon"],["netflix"],["aha"],["tesco"]])
obj=OrdinalEncoder()
result=obj.fit_transform(a)
result

array([[1.],
       [2.],
       [0.],
       [3.]])

In [29]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=asarray([["ok"],["chintu"],["rajesh"],["maddi"]])
obj=OneHotEncoder(sparse_output=False)
result=obj.fit_transform(a)
result

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [30]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=asarray([["amazon"],["netflix"],["aha"],["samsung"]])
obj=OneHotEncoder(drop="first",sparse_output=False)
result=obj.fit_transform(a)
result

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [31]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
a={
    "names":["amazon","aha","flipcart","tesco"],
     "values":["rajesh","maddi","today","tomorrow"]
}
df=pd.DataFrame(a)
obj=LabelEncoder()
df["names_n"]=obj.fit_transform(df["names"])
df["values_n"]=obj.fit_transform(df["values"])
df

names    values  names_n  values_n
0    amazon    rajesh        1         1
1       aha     maddi        0         0
2  flipcart     today        2         2
3     tesco  tomorrow        3         3

In [32]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
a={
    "x":[10,20,30,40,50],
     "y":[100,200,300,400,500]
}
df=pd.DataFrame(a)
obj=MinMaxScaler(feature_range=(0,1))
df[["x","y"]]=obj.fit_transform(df[["x","y"]])
df


x     y
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [33]:
import pandas as pd
import numpy as np
a={
    "houses":[234,678,456,999],
     "rent":[2,3,4,100]
}
df=pd.DataFrame(a)
cond1=df["rent"]<6
print(df[cond1])

   houses  rent
0     234     2
1     678     3
2     456     4


In [34]:
df["outliers"]=np.where(cond1,True,False)
df

houses  rent  outliers
0     234     2      True
1     678     3      True
2     456     4      True
3     999   100     False

In [35]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="median")
x=df[["marks"]].values
df[["marks"]]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3   77.5      M    average
4   70.0      M       good
5   77.5    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [36]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
a=asarray([["amazon"],["netflix"],["aha"]])
obj=OrdinalEncoder()
result=obj.fit_transform(a)
result

array([[1.],
       [2.],
       [0.]])

In [37]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=asarray([["banaan"],["apple"],["tree"],["waste"]])
obj=OneHotEncoder(drop="first",sparse_output=False)
result=obj.fit_transform(a)
result

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
import pandas as pd
df=pd.read_csv("sales2.csv")
df

Order id Customer name  Customer id                Product name  \
0      192837        Partha            8        Apple iPad 10.2-inch   
1      192838         Vinay           10               Flatscreen TV   
2      192839       Lavanya           16                20in Monitor   
3      192840         Mohan           24  Bose SoundSport Headphones   
4      192841         Kedar            2                Google Phone   
..        ...           ...          ...                         ...   
895    193732        Balaji           12          Samsung Galaxy S20   
896    193733       Neelima           19      27in 4K Gaming Monitor   
897    193734        Siddhu           18                Google Phone   
898    193735         Vinay           10                20in Monitor   
899    193736     Madhurima            7            27in FHD Monitor   

     Product cost  
0           59000  
1           65999  
2           75000  
3           55000  
4           59000  
..            ...  
895         60000  
896         75999  
897         69999  
898         69999  
899         55999  

[900 rows x 5 columns]

In [39]:
df.set_index("Product name",inplace=True)
df

Order id Customer name  Customer id  Product cost
Product name                                                                 
Apple iPad 10.2-inch          192837        Partha            8         59000
Flatscreen TV                 192838         Vinay           10         65999
20in Monitor                  192839       Lavanya           16         75000
Bose SoundSport Headphones    192840         Mohan           24         55000
Google Phone                  192841         Kedar            2         59000
...                              ...           ...          ...           ...
Samsung Galaxy S20            193732        Balaji           12         60000
27in 4K Gaming Monitor        193733       Neelima           19         75999
Google Phone                  193734        Siddhu           18         69999
20in Monitor                  193735         Vinay           10         69999
27in FHD Monitor              193736     Madhurima            7         55999

[900 rows x 4 columns]

In [40]:
rows=["Apple iPad 10.2-inch","Google Phone"]
cols=["Customer name","Customer name"]
df1=df.loc[rows,cols]
df1

Customer name Customer name
Product name                                    
Apple iPad 10.2-inch        Partha        Partha
Apple iPad 10.2-inch         Venki         Venki
Apple iPad 10.2-inch         Kedar         Kedar
Apple iPad 10.2-inch       Sumanth       Sumanth
Apple iPad 10.2-inch         Mohan         Mohan
...                            ...           ...
Google Phone               Karteek       Karteek
Google Phone               Karteek       Karteek
Google Phone           Mallikarjun   Mallikarjun
Google Phone            Chaithanya    Chaithanya
Google Phone                Siddhu        Siddhu

[103 rows x 2 columns]

In [41]:
df

Order id Customer name  Customer id  Product cost
Product name                                                                 
Apple iPad 10.2-inch          192837        Partha            8         59000
Flatscreen TV                 192838         Vinay           10         65999
20in Monitor                  192839       Lavanya           16         75000
Bose SoundSport Headphones    192840         Mohan           24         55000
Google Phone                  192841         Kedar            2         59000
...                              ...           ...          ...           ...
Samsung Galaxy S20            193732        Balaji           12         60000
27in 4K Gaming Monitor        193733       Neelima           19         75999
Google Phone                  193734        Siddhu           18         69999
20in Monitor                  193735         Vinay           10         69999
27in FHD Monitor              193736     Madhurima            7         55999

[900 rows x 4 columns]

In [42]:
df=pd.read_csv("sales4.csv")
df

Order_Id Customer_Name  Customer_Id                Product_Name  \
0           1023         Venki           15            27in FHD Monitor   
1           1024    Chaithanya           14                   iPhone 11   
2           1025        Shahid           20  Bose SoundSport Headphones   
3           1026         Veeru            3        Apple iPad 10.2-inch   
4           1027          Venu           23                Google Phone   
...          ...           ...          ...                         ...   
299995    301018       Karteek            4        Apple iPad 10.2-inch   
299996    301019         Veeru            3          Macbook Pro Laptop   
299997    301020        Harsha            5          LG Washing Machine   
299998    301021    Nireekshan            1                   LG Mobile   
299999    301022       Pradhan           17      34in Ultrawide Monitor   

        Product_Cost  
0              59000  
1              69000  
2              65999  
3              63999  
4              63999  
...              ...  
299995         51999  
299996         51999  
299997         65000  
299998         60000  
299999         55000  

[300000 rows x 5 columns]

In [43]:
df=pd.read_csv("sales4.csv")
df

Order_Id Customer_Name  Customer_Id                Product_Name  \
0           1023         Venki           15            27in FHD Monitor   
1           1024    Chaithanya           14                   iPhone 11   
2           1025        Shahid           20  Bose SoundSport Headphones   
3           1026         Veeru            3        Apple iPad 10.2-inch   
4           1027          Venu           23                Google Phone   
...          ...           ...          ...                         ...   
299995    301018       Karteek            4        Apple iPad 10.2-inch   
299996    301019         Veeru            3          Macbook Pro Laptop   
299997    301020        Harsha            5          LG Washing Machine   
299998    301021    Nireekshan            1                   LG Mobile   
299999    301022       Pradhan           17      34in Ultrawide Monitor   

        Product_Cost  
0              59000  
1              69000  
2              65999  
3              63999  
4              63999  
...              ...  
299995         51999  
299996         51999  
299997         65000  
299998         60000  
299999         55000  

[300000 rows x 5 columns]

In [44]:
cond1=df["Customer_Name"]=="Karteek"
cond2=df["Product_Name"]=="Google Phone"
print(df[cond1&cond2])

        Order_Id Customer_Name  Customer_Id  Product_Name  Product_Cost
401         1424       Karteek            4  Google Phone         63999
480         1503       Karteek            4  Google Phone         65999
1223        2246       Karteek            4  Google Phone         55000
1238        2261       Karteek            4  Google Phone         65999
2079        3102       Karteek            4  Google Phone         61000
...          ...           ...          ...           ...           ...
296853    297876       Karteek            4  Google Phone         59000
296891    297914       Karteek            4  Google Phone         65999
297568    298591       Karteek            4  Google Phone         50000
299297    300320       Karteek            4  Google Phone         55000
299734    300757       Karteek            4  Google Phone         55000

[612 rows x 5 columns]


In [45]:
cond1=df["Customer_Name"]=="Shahid"
cond2=df["Product_Name"]=="LG Mobile"
df1=df.loc[cond1&cond2]
df1

Order_Id Customer_Name  Customer_Id Product_Name  Product_Cost
1246        2269        Shahid           20    LG Mobile         55000
1946        2969        Shahid           20    LG Mobile         75999
2370        3393        Shahid           20    LG Mobile         60000
3117        4140        Shahid           20    LG Mobile         61000
3146        4169        Shahid           20    LG Mobile         61000
...          ...           ...          ...          ...           ...
297233    298256        Shahid           20    LG Mobile         60000
297979    299002        Shahid           20    LG Mobile         65999
298115    299138        Shahid           20    LG Mobile         65000
298482    299505        Shahid           20    LG Mobile         51999
299880    300903        Shahid           20    LG Mobile         65999

[589 rows x 5 columns]

In [46]:
a=["iPhone 11","Apple iPad 10.2-inch","LG Washing Machine"]
b=df["Product_Name"].isin(a)
df1=df[b]
df1

Order_Id Customer_Name  Customer_Id          Product_Name  \
1           1024    Chaithanya           14             iPhone 11   
3           1026         Veeru            3  Apple iPad 10.2-inch   
6           1029          Venu           23             iPhone 11   
9           1032       Neelima           19    LG Washing Machine   
24          1047         Shafi           25    LG Washing Machine   
...          ...           ...          ...                   ...   
299954    300977     Madhurima            7             iPhone 11   
299956    300979       Neelima           19             iPhone 11   
299990    301013        Balaji           12             iPhone 11   
299995    301018       Karteek            4  Apple iPad 10.2-inch   
299997    301020        Harsha            5    LG Washing Machine   

        Product_Cost  
1              69000  
3              63999  
6              61000  
9              63000  
24             63999  
...              ...  
299954         75999  
299956         65999  
299990         65999  
299995         51999  
299997         65000  

[44761 rows x 5 columns]

In [47]:
df1=df.index[10:15]
df2=["Customer_Name","Product_Name"]
result=df.loc[df1,df2]
result

Customer_Name              Product_Name
10         Vijay                 iPhone 7s
11         Tarun        Samsung Galaxy S20
12         Kedar              Google Phone
13    Chaithanya    LG ThinQ Refrigerator 
14    Nireekshan  Apple Airpods Headphones

In [48]:
df=pd.read_csv("sales7_dates.csv")
df

Order_Id Customer_Name  Customer_Id                Product_Name  \
0         1023         Venki           15            27in FHD Monitor   
1         1024    Chaithanya           14                   iPhone 11   
2         1025        Shahid           20  Bose SoundSport Headphones   
3         1026         Veeru            3        Apple iPad 10.2-inch   
4         1027          Venu           23                Google Phone   
...        ...           ...          ...                         ...   
9994     11017       Karteek            4                20in Monitor   
9995     11018         Vinay           10    Apple Airpods Headphones   
9996     11019       Neelima           19      LG ThinQ Refrigerator    
9997     11020        Siddhu           18                   iPhone 7s   
9998     11021         Tarun           11      34in Ultrawide Monitor   

      Product_Cost         Pur_Date  
0            59000    1/1/2019 0:00  
1            69000    1/1/2019 1:00  
2            65999    1/1/2019 2:00  
3            63999    1/1/2019 3:00  
4            63999    1/1/2019 4:00  
...            ...              ...  
9994         51999  2/21/2020 10:00  
9995         75999  2/21/2020 11:00  
9996         75999  2/21/2020 12:00  
9997         65999  2/21/2020 13:00  
9998         55000  2/21/2020 14:00  

[9999 rows x 6 columns]

In [49]:
df["Pur_Date"]=pd.to_datetime(df["Pur_Date"])
df

Order_Id Customer_Name  Customer_Id                Product_Name  \
0         1023         Venki           15            27in FHD Monitor   
1         1024    Chaithanya           14                   iPhone 11   
2         1025        Shahid           20  Bose SoundSport Headphones   
3         1026         Veeru            3        Apple iPad 10.2-inch   
4         1027          Venu           23                Google Phone   
...        ...           ...          ...                         ...   
9994     11017       Karteek            4                20in Monitor   
9995     11018         Vinay           10    Apple Airpods Headphones   
9996     11019       Neelima           19      LG ThinQ Refrigerator    
9997     11020        Siddhu           18                   iPhone 7s   
9998     11021         Tarun           11      34in Ultrawide Monitor   

      Product_Cost            Pur_Date  
0            59000 2019-01-01 00:00:00  
1            69000 2019-01-01 01:00:00  
2            65999 2019-01-01 02:00:00  
3            63999 2019-01-01 03:00:00  
4            63999 2019-01-01 04:00:00  
...            ...                 ...  
9994         51999 2020-02-21 10:00:00  
9995         75999 2020-02-21 11:00:00  
9996         75999 2020-02-21 12:00:00  
9997         65999 2020-02-21 13:00:00  
9998         55000 2020-02-21 14:00:00  

[9999 rows x 6 columns]

In [50]:
df.dtypes

Order_Id                  int64
Customer_Name            object
Customer_Id               int64
Product_Name             object
Product_Cost              int64
Pur_Date         datetime64[ns]
dtype: object

In [51]:
df["Pur_Date"].dt.day_name()

0       Tuesday
1       Tuesday
2       Tuesday
3       Tuesday
4       Tuesday
         ...   
9994     Friday
9995     Friday
9996     Friday
9997     Friday
9998     Friday
Name: Pur_Date, Length: 9999, dtype: object

In [52]:
df["Pur_Date"].dt.month_name()

0        January
1        January
2        January
3        January
4        January
          ...   
9994    February
9995    February
9996    February
9997    February
9998    February
Name: Pur_Date, Length: 9999, dtype: object

In [53]:
df["Pur_Date"].dt.weekday+1

0       2
1       2
2       2
3       2
4       2
       ..
9994    5
9995    5
9996    5
9997    5
9998    5
Name: Pur_Date, Length: 9999, dtype: int32

In [54]:
df["day"]=df["Pur_Date"].dt.day

In [55]:
df

Order_Id Customer_Name  Customer_Id                Product_Name  \
0         1023         Venki           15            27in FHD Monitor   
1         1024    Chaithanya           14                   iPhone 11   
2         1025        Shahid           20  Bose SoundSport Headphones   
3         1026         Veeru            3        Apple iPad 10.2-inch   
4         1027          Venu           23                Google Phone   
...        ...           ...          ...                         ...   
9994     11017       Karteek            4                20in Monitor   
9995     11018         Vinay           10    Apple Airpods Headphones   
9996     11019       Neelima           19      LG ThinQ Refrigerator    
9997     11020        Siddhu           18                   iPhone 7s   
9998     11021         Tarun           11      34in Ultrawide Monitor   

      Product_Cost            Pur_Date  day  
0            59000 2019-01-01 00:00:00    1  
1            69000 2019-01-01 01:00:00    1  
2            65999 2019-01-01 02:00:00    1  
3            63999 2019-01-01 03:00:00    1  
4            63999 2019-01-01 04:00:00    1  
...            ...                 ...  ...  
9994         51999 2020-02-21 10:00:00   21  
9995         75999 2020-02-21 11:00:00   21  
9996         75999 2020-02-21 12:00:00   21  
9997         65999 2020-02-21 13:00:00   21  
9998         55000 2020-02-21 14:00:00   21  

[9999 rows x 7 columns]

In [56]:
df.set_index("Pur_Date",inplace=True)
df

Order_Id Customer_Name  Customer_Id  \
Pur_Date                                                   
2019-01-01 00:00:00      1023         Venki           15   
2019-01-01 01:00:00      1024    Chaithanya           14   
2019-01-01 02:00:00      1025        Shahid           20   
2019-01-01 03:00:00      1026         Veeru            3   
2019-01-01 04:00:00      1027          Venu           23   
...                       ...           ...          ...   
2020-02-21 10:00:00     11017       Karteek            4   
2020-02-21 11:00:00     11018         Vinay           10   
2020-02-21 12:00:00     11019       Neelima           19   
2020-02-21 13:00:00     11020        Siddhu           18   
2020-02-21 14:00:00     11021         Tarun           11   

                                   Product_Name  Product_Cost  day  
Pur_Date                                                            
2019-01-01 00:00:00            27in FHD Monitor         59000    1  
2019-01-01 01:00:00                   iPhone 11         69000    1  
2019-01-01 02:00:00  Bose SoundSport Headphones         65999    1  
2019-01-01 03:00:00        Apple iPad 10.2-inch         63999    1  
2019-01-01 04:00:00                Google Phone         63999    1  
...                                         ...           ...  ...  
2020-02-21 10:00:00                20in Monitor         51999   21  
2020-02-21 11:00:00    Apple Airpods Headphones         75999   21  
2020-02-21 12:00:00      LG ThinQ Refrigerator          75999   21  
2020-02-21 13:00:00                   iPhone 7s         65999   21  
2020-02-21 14:00:00      34in Ultrawide Monitor         55000   21  

[9999 rows x 6 columns]

In [57]:
df1=df.last('10D')
df1

C:\Users\rajes\AppData\Local\Temp\ipykernel_1668\3498549514.py:1: FutureWarning: last is deprecated and will be removed in a future version. Please create a mask and filter using `.loc` instead
  df1=df.last('10D')


Order_Id Customer_Name  Customer_Id  \
Pur_Date                                                   
2020-02-11 15:00:00     10782        Harsha            5   
2020-02-11 16:00:00     10783         Veeru            3   
2020-02-11 17:00:00     10784         Vinay           10   
2020-02-11 18:00:00     10785  Jaya Chandra           21   
2020-02-11 19:00:00     10786        Shahid           20   
...                       ...           ...          ...   
2020-02-21 10:00:00     11017       Karteek            4   
2020-02-21 11:00:00     11018         Vinay           10   
2020-02-21 12:00:00     11019       Neelima           19   
2020-02-21 13:00:00     11020        Siddhu           18   
2020-02-21 14:00:00     11021         Tarun           11   

                                 Product_Name  Product_Cost  day  
Pur_Date                                                          
2020-02-11 15:00:00              Google Phone         75000   11  
2020-02-11 16:00:00              Google Phone         61000   11  
2020-02-11 17:00:00    34in Ultrawide Monitor         69999   11  
2020-02-11 18:00:00           ThinkPad Laptop         50000   11  
2020-02-11 19:00:00                 iPhone 11         51999   11  
...                                       ...           ...  ...  
2020-02-21 10:00:00              20in Monitor         51999   21  
2020-02-21 11:00:00  Apple Airpods Headphones         75999   21  
2020-02-21 12:00:00    LG ThinQ Refrigerator          75999   21  
2020-02-21 13:00:00                 iPhone 7s         65999   21  
2020-02-21 14:00:00    34in Ultrawide Monitor         55000   21  

[240 rows x 6 columns]

In [58]:
df1=df.last('20D')
df1

C:\Users\rajes\AppData\Local\Temp\ipykernel_1668\1543814517.py:1: FutureWarning: last is deprecated and will be removed in a future version. Please create a mask and filter using `.loc` instead
  df1=df.last('20D')


Order_Id Customer_Name  Customer_Id  \
Pur_Date                                                   
2020-02-01 15:00:00     10542         Mohan           24   
2020-02-01 16:00:00     10543    Nireekshan            1   
2020-02-01 17:00:00     10544   Mallikarjun           13   
2020-02-01 18:00:00     10545     Madhurima            7   
2020-02-01 19:00:00     10546     Madhurima            7   
...                       ...           ...          ...   
2020-02-21 10:00:00     11017       Karteek            4   
2020-02-21 11:00:00     11018         Vinay           10   
2020-02-21 12:00:00     11019       Neelima           19   
2020-02-21 13:00:00     11020        Siddhu           18   
2020-02-21 14:00:00     11021         Tarun           11   

                                 Product_Name  Product_Cost  day  
Pur_Date                                                          
2020-02-01 15:00:00                 LG Mobile         65000    1  
2020-02-01 16:00:00             Flatscreen TV         50000    1  
2020-02-01 17:00:00             Flatscreen TV         65999    1  
2020-02-01 18:00:00    Samsung Galaxy S9 Plus         69999    1  
2020-02-01 19:00:00                  iPhone 8         55999    1  
...                                       ...           ...  ...  
2020-02-21 10:00:00              20in Monitor         51999   21  
2020-02-21 11:00:00  Apple Airpods Headphones         75999   21  
2020-02-21 12:00:00    LG ThinQ Refrigerator          75999   21  
2020-02-21 13:00:00                 iPhone 7s         65999   21  
2020-02-21 14:00:00    34in Ultrawide Monitor         55000   21  

[480 rows x 6 columns]

In [59]:
df=pd.read_csv("sales7_dates.csv",parse_dates=["Pur_Date"])
df

Order_Id Customer_Name  Customer_Id                Product_Name  \
0         1023         Venki           15            27in FHD Monitor   
1         1024    Chaithanya           14                   iPhone 11   
2         1025        Shahid           20  Bose SoundSport Headphones   
3         1026         Veeru            3        Apple iPad 10.2-inch   
4         1027          Venu           23                Google Phone   
...        ...           ...          ...                         ...   
9994     11017       Karteek            4                20in Monitor   
9995     11018         Vinay           10    Apple Airpods Headphones   
9996     11019       Neelima           19      LG ThinQ Refrigerator    
9997     11020        Siddhu           18                   iPhone 7s   
9998     11021         Tarun           11      34in Ultrawide Monitor   

      Product_Cost            Pur_Date  
0            59000 2019-01-01 00:00:00  
1            69000 2019-01-01 01:00:00  
2            65999 2019-01-01 02:00:00  
3            63999 2019-01-01 03:00:00  
4            63999 2019-01-01 04:00:00  
...            ...                 ...  
9994         51999 2020-02-21 10:00:00  
9995         75999 2020-02-21 11:00:00  
9996         75999 2020-02-21 12:00:00  
9997         65999 2020-02-21 13:00:00  
9998         55000 2020-02-21 14:00:00  

[9999 rows x 6 columns]

In [60]:
cond1=df["Pur_Date"]>"2019-01-01 00:00:00"
cond2=df["Pur_Date"]<"2019-01-01 04:00:00"
(df[cond1&cond2])

Order_Id Customer_Name  Customer_Id                Product_Name  \
1      1024    Chaithanya           14                   iPhone 11   
2      1025        Shahid           20  Bose SoundSport Headphones   
3      1026         Veeru            3        Apple iPad 10.2-inch   

   Product_Cost            Pur_Date  
1         69000 2019-01-01 01:00:00  
2         65999 2019-01-01 02:00:00  
3         63999 2019-01-01 03:00:00

In [61]:
import pandas as pd
import os
a="./daniel"
all_files=os.listdir(a)
all_files

['apr_sales.csv',
 'aug_sales.csv',
 'dec_sales.csv',
 'feb_sales.csv',
 'fun.jpg',
 'jan_sales.csv',
 'jul_sales.csv',
 'jun_sales.csv',
 'mar_sales.csv',
 'may_sales.csv',
 'nov_sales.csv',
 'oct_sales.csv',
 'progress.txt',
 'sep_sales.csv',
 'status.xlsx']

In [62]:
import pandas as pd
import os
a="./daniel"
all_files=os.listdir(a)
csv_files=filter(lambda a:a.endswith(".csv"),all_files)
list(csv_files)

['apr_sales.csv',
 'aug_sales.csv',
 'dec_sales.csv',
 'feb_sales.csv',
 'jan_sales.csv',
 'jul_sales.csv',
 'jun_sales.csv',
 'mar_sales.csv',
 'may_sales.csv',
 'nov_sales.csv',
 'oct_sales.csv',
 'sep_sales.csv']

In [63]:
import os
import pandas as pd
import glob
a="./daniel"
all_files=os.path.join(a,"*csv")
files=glob.glob(all_files)
df=[pd.read_csv(file) for file in files]
result=pd.concat(df,ignore_index=False)
result

Order_Id Customer_Name  Customer_Id                Product_Name  \
0       1320          Venu           23      LG ThinQ Refrigerator    
1       1321  Jaya Chandra           21  Bose SoundSport Headphones   
2       1322   Mallikarjun           13    Apple Airpods Headphones   
3       1323        Siddhu           18      Samsung Galaxy S9 Plus   
4       1324        Daniel            6                    iPhone 8   
..       ...           ...          ...                         ...   
4       1819        Daniel            6          LG Washing Machine   
5       1820       Neelima           19                20in Monitor   
6       1821       Karteek            4                20in Monitor   
7       1822  Jaya Chandra           21      LG ThinQ Refrigerator    
8       1823    Chaithanya           14            27in FHD Monitor   

    Product_Cost             Date  
0          55000   4/11/2019 9:00  
1          63000  4/13/2019 10:00  
2          69999  4/13/2019 11:00  
3          55000  4/14/2019 12:00  
4          55000  4/15/2019 13:00  
..           ...              ...  
4          50000    9/3/2019 4:00  
5          55000    9/3/2019 5:00  
6          50000    9/3/2019 6:00  
7          75999    9/3/2019 7:00  
8          55000    9/3/2019 8:00  

[108 rows x 6 columns]

In [64]:
final=result.groupby("Customer_Name")["Product_Name"].value_counts()
final

Customer_Name  Product_Name            
Balaji         Apple Airpods Headphones    1
               Google Phone                1
               LG Mobile                   1
               Samsung Galaxy S9 Plus      1
               iPhone 11                   1
                                          ..
Venu           iPhone 9                    1
Vijay          Flatscreen TV               1
               Macbook Pro Laptop          1
Vinay          27in FHD Monitor            1
               LG Mobile                   1
Name: count, Length: 97, dtype: int64

In [65]:
result

Order_Id Customer_Name  Customer_Id                Product_Name  \
0       1320          Venu           23      LG ThinQ Refrigerator    
1       1321  Jaya Chandra           21  Bose SoundSport Headphones   
2       1322   Mallikarjun           13    Apple Airpods Headphones   
3       1323        Siddhu           18      Samsung Galaxy S9 Plus   
4       1324        Daniel            6                    iPhone 8   
..       ...           ...          ...                         ...   
4       1819        Daniel            6          LG Washing Machine   
5       1820       Neelima           19                20in Monitor   
6       1821       Karteek            4                20in Monitor   
7       1822  Jaya Chandra           21      LG ThinQ Refrigerator    
8       1823    Chaithanya           14            27in FHD Monitor   

    Product_Cost             Date  
0          55000   4/11/2019 9:00  
1          63000  4/13/2019 10:00  
2          69999  4/13/2019 11:00  
3          55000  4/14/2019 12:00  
4          55000  4/15/2019 13:00  
..           ...              ...  
4          50000    9/3/2019 4:00  
5          55000    9/3/2019 5:00  
6          50000    9/3/2019 6:00  
7          75999    9/3/2019 7:00  
8          55000    9/3/2019 8:00  

[108 rows x 6 columns]

In [67]:
final1=result.groupby(["Customer_Name","Product_Cost"]).sum()
final1

Order_Id  Customer_Id              Product_Name  \
Customer_Name Product_Cost                                                    
Balaji        50000             2020           12                 LG Mobile   
              59000             1917           12                 iPhone 11   
              60000             1229           12  Apple Airpods Headphones   
              63999             1818           12    Samsung Galaxy S9 Plus   
              65999             1123           12              Google Phone   
...                              ...          ...                       ...   
Venu          63999             1027           23              Google Phone   
Vijay         50000             1722            9        Macbook Pro Laptop   
              51999             1723            9             Flatscreen TV   
Vinay         69000             1125           10          27in FHD Monitor   
              75999             2116           10                 LG Mobile   

                                        Date  
Customer_Name Product_Cost                    
Balaji        50000          11/2/2019 13:00  
              59000           10/8/2019 6:00  
              60000           3/9/2019 14:00  
              63999            9/3/2019 3:00  
              65999            2/5/2019 4:00  
...                                      ...  
Venu          63999            1/2/2019 4:00  
Vijay         50000           8/30/2019 3:00  
              51999           8/30/2019 4:00  
Vinay         69000            2/6/2019 6:00  
              75999         12/16/2019 13:00  

[93 rows x 4 columns]

In [68]:
result

Order_Id Customer_Name  Customer_Id                Product_Name  \
0       1320          Venu           23      LG ThinQ Refrigerator    
1       1321  Jaya Chandra           21  Bose SoundSport Headphones   
2       1322   Mallikarjun           13    Apple Airpods Headphones   
3       1323        Siddhu           18      Samsung Galaxy S9 Plus   
4       1324        Daniel            6                    iPhone 8   
..       ...           ...          ...                         ...   
4       1819        Daniel            6          LG Washing Machine   
5       1820       Neelima           19                20in Monitor   
6       1821       Karteek            4                20in Monitor   
7       1822  Jaya Chandra           21      LG ThinQ Refrigerator    
8       1823    Chaithanya           14            27in FHD Monitor   

    Product_Cost             Date  
0          55000   4/11/2019 9:00  
1          63000  4/13/2019 10:00  
2          69999  4/13/2019 11:00  
3          55000  4/14/2019 12:00  
4          55000  4/15/2019 13:00  
..           ...              ...  
4          50000    9/3/2019 4:00  
5          55000    9/3/2019 5:00  
6          50000    9/3/2019 6:00  
7          75999    9/3/2019 7:00  
8          55000    9/3/2019 8:00  

[108 rows x 6 columns]

In [69]:
a={
    "Product_Cost":["max","min","sum"]
}
final2=result.groupby("Product_Name").agg(a)
final2

Product_Cost               
                                    max    min     sum
Product_Name                                          
20in Monitor                      65999  50000  281998
27in 4K Gaming Monitor            63999  55999  119998
27in FHD Monitor                  75999  55000  666997
34in Ultrawide Monitor            61000  50000  272999
Apple Airpods Headphones          75000  50000  378999
Apple iPad 10.2-inch              63999  50000  174999
Bose SoundSport Headphones        65999  63000  193999
Flatscreen TV                     75999  51999  378997
Google Phone                      65999  50000  373995
LG Mobile                         75999  50000  571997
LG ThinQ Refrigerator             75999  55000  193999
LG Washing Machine                75999  50000  354997
Macbook Pro Laptop                65000  50000  226000
Samsung Galaxy S20                63999  55000  173999
Samsung Galaxy S9 Plus            75000  50000  362998
ThinkPad Laptop                   65000  55000  294999
iPhone 11                         69000  55999  491999
iPhone 7s                         69999  55999  181997
iPhone 8                          65999  50000  415997
iPhone 9                          69999  50000  487995

In [72]:
import pandas as pd
d1 = {
      "Id": [1, 2, 3, 4, 5, 6],
      "Name": ["Pradhan", "Venu", "Madhurima", "Nireekshan",
                  "Shafi", "Veeru"],
       "Subject": ["English", "Java", "Html", "Python", "C", "dot net"]
                       
     }
d2 =  {
          "Id": [11, 12, 13, 14, 15, 16],
         "Name": ["Srinu", "Sumanth", "Neelima", "Daniel", "Arjun",
                   "Veeru"],
         "Subject": ["Java", "Html", "Cpp", "Python", "C", "dot net"]
         }
df1=pd.DataFrame(d1)
df2=pd.DataFrame(d2)
result=pd.merge(df1,df2,on="Subject",how="left")
result

Id_x      Name_x  Subject  Id_y   Name_y
0     1     Pradhan  English   NaN      NaN
1     2        Venu     Java  11.0    Srinu
2     3   Madhurima     Html  12.0  Sumanth
3     4  Nireekshan   Python  14.0   Daniel
4     5       Shafi        C  15.0    Arjun
5     6       Veeru  dot net  16.0    Veeru

In [73]:
df=pd.read_csv("sales8.csv")
df

Order Id Customer name  Customer Id                Product name  \
0     192837         Veeru            3                   LG Mobile   
1     192838       Neelima           19        Apple iPad 10.2-inch   
2     192839        Balaji           12      34in Ultrawide Monitor   
3     192840        Shahid           20                   iPhone 11   
4     192841         Vinay           10  Bose SoundSport Headphones   
5     192842         Vinay           10                20in Monitor   
6     192843        Balaji           12                    iPhone 8   
7     192844    Nireekshan            1      27in 4K Gaming Monitor   
8     192845          Venu           23                    iPhone 9   
9     192846         Veeru            3                20in Monitor   
10    192847     Madhurima            7               Flatscreen TV   
11    192848         Kedar            2               Flatscreen TV   
12    192849          Venu           23          Samsung Galaxy S20   
13    192850       Neelima           19             ThinkPad Laptop   
14    192851        Daniel            6      Samsung Galaxy S9 Plus   
15    192852         Veeru            3                    iPhone 9   
16    192853       Lavanya           16                   iPhone 7s   
17    192854   Mallikarjun           13                   LG Mobile   
18    192855         Vijay            9      Samsung Galaxy S9 Plus   
19    192856       Karteek            4                    iPhone 8   
20    192857         Mohan           24          Macbook Pro Laptop   
21    192858          Venu           23  Bose SoundSport Headphones   
22    192859     Madhurima            7          LG Washing Machine   
23    192860         Venki           15                    iPhone 8   
24    192861         Veeru            3          Samsung Galaxy S20   
25    192862    Nireekshan            1               Flatscreen TV   
26    192863        Daniel            6                    iPhone 8   
27    192864         Kedar            2                Google Phone   
28    192865     Madhurima            7      LG ThinQ Refrigerator    
29    192866       Karteek            4                    iPhone 8   

    Product cost  Quantity  
0          65999         1  
1          63000         2  
2          75999         1  
3          60000         2  
4          69999         3  
5          65999         2  
6          55999         3  
7          55999         3  
8          55999         2  
9          63000         1  
10         63000         1  
11         63999         2  
12         65999         2  
13         60000         2  
14         69999         1  
15         60000         2  
16         55000         1  
17         65999         1  
18         69000         2  
19         65000         2  
20         59000         1  
21         63000         1  
22         69000         1  
23         60000         1  
24         51999         2  
25         75999         2  
26         69000         1  
27         60000         1  
28         61000         1  
29         50000         2

In [74]:
df["totalvalue"]=df["Product cost"]*df["Quantity"]
df

Order Id Customer name  Customer Id                Product name  \
0     192837         Veeru            3                   LG Mobile   
1     192838       Neelima           19        Apple iPad 10.2-inch   
2     192839        Balaji           12      34in Ultrawide Monitor   
3     192840        Shahid           20                   iPhone 11   
4     192841         Vinay           10  Bose SoundSport Headphones   
5     192842         Vinay           10                20in Monitor   
6     192843        Balaji           12                    iPhone 8   
7     192844    Nireekshan            1      27in 4K Gaming Monitor   
8     192845          Venu           23                    iPhone 9   
9     192846         Veeru            3                20in Monitor   
10    192847     Madhurima            7               Flatscreen TV   
11    192848         Kedar            2               Flatscreen TV   
12    192849          Venu           23          Samsung Galaxy S20   
13    192850       Neelima           19             ThinkPad Laptop   
14    192851        Daniel            6      Samsung Galaxy S9 Plus   
15    192852         Veeru            3                    iPhone 9   
16    192853       Lavanya           16                   iPhone 7s   
17    192854   Mallikarjun           13                   LG Mobile   
18    192855         Vijay            9      Samsung Galaxy S9 Plus   
19    192856       Karteek            4                    iPhone 8   
20    192857         Mohan           24          Macbook Pro Laptop   
21    192858          Venu           23  Bose SoundSport Headphones   
22    192859     Madhurima            7          LG Washing Machine   
23    192860         Venki           15                    iPhone 8   
24    192861         Veeru            3          Samsung Galaxy S20   
25    192862    Nireekshan            1               Flatscreen TV   
26    192863        Daniel            6                    iPhone 8   
27    192864         Kedar            2                Google Phone   
28    192865     Madhurima            7      LG ThinQ Refrigerator    
29    192866       Karteek            4                    iPhone 8   

    Product cost  Quantity  totalvalue  
0          65999         1       65999  
1          63000         2      126000  
2          75999         1       75999  
3          60000         2      120000  
4          69999         3      209997  
5          65999         2      131998  
6          55999         3      167997  
7          55999         3      167997  
8          55999         2      111998  
9          63000         1       63000  
10         63000         1       63000  
11         63999         2      127998  
12         65999         2      131998  
13         60000         2      120000  
14         69999         1       69999  
15         60000         2      120000  
16         55000         1       55000  
17         65999         1       65999  
18         69000         2      138000  
19         65000         2      130000  
20         59000         1       59000  
21         63000         1       63000  
22         69000         1       69000  
23         60000         1       60000  
24         51999         2      103998  
25         75999         2      151998  
26         69000         1       69000  
27         60000         1       60000  
28         61000         1       61000  
29         50000         2      100000

In [78]:
a="newvalue"
df.insert(3,"value1",a)
df

Order Id Customer name  Customer Id    value1 error  \
0     192837         Veeru            3  newvalue     a   
1     192838       Neelima           19  newvalue     a   
2     192839        Balaji           12  newvalue     a   
3     192840        Shahid           20  newvalue     a   
4     192841         Vinay           10  newvalue     a   
5     192842         Vinay           10  newvalue     a   
6     192843        Balaji           12  newvalue     a   
7     192844    Nireekshan            1  newvalue     a   
8     192845          Venu           23  newvalue     a   
9     192846         Veeru            3  newvalue     a   
10    192847     Madhurima            7  newvalue     a   
11    192848         Kedar            2  newvalue     a   
12    192849          Venu           23  newvalue     a   
13    192850       Neelima           19  newvalue     a   
14    192851        Daniel            6  newvalue     a   
15    192852         Veeru            3  newvalue     a   
16    192853       Lavanya           16  newvalue     a   
17    192854   Mallikarjun           13  newvalue     a   
18    192855         Vijay            9  newvalue     a   
19    192856       Karteek            4  newvalue     a   
20    192857         Mohan           24  newvalue     a   
21    192858          Venu           23  newvalue     a   
22    192859     Madhurima            7  newvalue     a   
23    192860         Venki           15  newvalue     a   
24    192861         Veeru            3  newvalue     a   
25    192862    Nireekshan            1  newvalue     a   
26    192863        Daniel            6  newvalue     a   
27    192864         Kedar            2  newvalue     a   
28    192865     Madhurima            7  newvalue     a   
29    192866       Karteek            4  newvalue     a   

                  Product name  Product cost  Quantity  totalvalue  
0                    LG Mobile         65999         1       65999  
1         Apple iPad 10.2-inch         63000         2      126000  
2       34in Ultrawide Monitor         75999         1       75999  
3                    iPhone 11         60000         2      120000  
4   Bose SoundSport Headphones         69999         3      209997  
5                 20in Monitor         65999         2      131998  
6                     iPhone 8         55999         3      167997  
7       27in 4K Gaming Monitor         55999         3      167997  
8                     iPhone 9         55999         2      111998  
9                 20in Monitor         63000         1       63000  
10               Flatscreen TV         63000         1       63000  
11               Flatscreen TV         63999         2      127998  
12          Samsung Galaxy S20         65999         2      131998  
13             ThinkPad Laptop         60000         2      120000  
14      Samsung Galaxy S9 Plus         69999         1       69999  
15                    iPhone 9         60000         2      120000  
16                   iPhone 7s         55000         1       55000  
17                   LG Mobile         65999         1       65999  
18      Samsung Galaxy S9 Plus         69000         2      138000  
19                    iPhone 8         65000         2      130000  
20          Macbook Pro Laptop         59000         1       59000  
21  Bose SoundSport Headphones         63000         1       63000  
22          LG Washing Machine         69000         1       69000  
23                    iPhone 8         60000         1       60000  
24          Samsung Galaxy S20         51999         2      103998  
25               Flatscreen TV         75999         2      151998  
26                    iPhone 8         69000         1       69000  
27                Google Phone         60000         1       60000  
28      LG ThinQ Refrigerator          61000         1       61000  
29                    iPhone 8         50000         2      100000

In [80]:
df.drop(columns="error",inplace=True)
df

Order Id Customer name  Customer Id    value1                Product name  \
0     192837         Veeru            3  newvalue                   LG Mobile   
1     192838       Neelima           19  newvalue        Apple iPad 10.2-inch   
2     192839        Balaji           12  newvalue      34in Ultrawide Monitor   
3     192840        Shahid           20  newvalue                   iPhone 11   
4     192841         Vinay           10  newvalue  Bose SoundSport Headphones   
5     192842         Vinay           10  newvalue                20in Monitor   
6     192843        Balaji           12  newvalue                    iPhone 8   
7     192844    Nireekshan            1  newvalue      27in 4K Gaming Monitor   
8     192845          Venu           23  newvalue                    iPhone 9   
9     192846         Veeru            3  newvalue                20in Monitor   
10    192847     Madhurima            7  newvalue               Flatscreen TV   
11    192848         Kedar            2  newvalue               Flatscreen TV   
12    192849          Venu           23  newvalue          Samsung Galaxy S20   
13    192850       Neelima           19  newvalue             ThinkPad Laptop   
14    192851        Daniel            6  newvalue      Samsung Galaxy S9 Plus   
15    192852         Veeru            3  newvalue                    iPhone 9   
16    192853       Lavanya           16  newvalue                   iPhone 7s   
17    192854   Mallikarjun           13  newvalue                   LG Mobile   
18    192855         Vijay            9  newvalue      Samsung Galaxy S9 Plus   
19    192856       Karteek            4  newvalue                    iPhone 8   
20    192857         Mohan           24  newvalue          Macbook Pro Laptop   
21    192858          Venu           23  newvalue  Bose SoundSport Headphones   
22    192859     Madhurima            7  newvalue          LG Washing Machine   
23    192860         Venki           15  newvalue                    iPhone 8   
24    192861         Veeru            3  newvalue          Samsung Galaxy S20   
25    192862    Nireekshan            1  newvalue               Flatscreen TV   
26    192863        Daniel            6  newvalue                    iPhone 8   
27    192864         Kedar            2  newvalue                Google Phone   
28    192865     Madhurima            7  newvalue      LG ThinQ Refrigerator    
29    192866       Karteek            4  newvalue                    iPhone 8   

    Product cost  Quantity  totalvalue  
0          65999         1       65999  
1          63000         2      126000  
2          75999         1       75999  
3          60000         2      120000  
4          69999         3      209997  
5          65999         2      131998  
6          55999         3      167997  
7          55999         3      167997  
8          55999         2      111998  
9          63000         1       63000  
10         63000         1       63000  
11         63999         2      127998  
12         65999         2      131998  
13         60000         2      120000  
14         69999         1       69999  
15         60000         2      120000  
16         55000         1       55000  
17         65999         1       65999  
18         69000         2      138000  
19         65000         2      130000  
20         59000         1       59000  
21         63000         1       63000  
22         69000         1       69000  
23         60000         1       60000  
24         51999         2      103998  
25         75999         2      151998  
26         69000         1       69000  
27         60000         1       60000  
28         61000         1       61000  
29         50000         2      100000

In [81]:
cols=["value1","totalvalue"]
df.drop(cols,axis=1,inplace=True)

In [82]:
df

Order Id Customer name  Customer Id                Product name  \
0     192837         Veeru            3                   LG Mobile   
1     192838       Neelima           19        Apple iPad 10.2-inch   
2     192839        Balaji           12      34in Ultrawide Monitor   
3     192840        Shahid           20                   iPhone 11   
4     192841         Vinay           10  Bose SoundSport Headphones   
5     192842         Vinay           10                20in Monitor   
6     192843        Balaji           12                    iPhone 8   
7     192844    Nireekshan            1      27in 4K Gaming Monitor   
8     192845          Venu           23                    iPhone 9   
9     192846         Veeru            3                20in Monitor   
10    192847     Madhurima            7               Flatscreen TV   
11    192848         Kedar            2               Flatscreen TV   
12    192849          Venu           23          Samsung Galaxy S20   
13    192850       Neelima           19             ThinkPad Laptop   
14    192851        Daniel            6      Samsung Galaxy S9 Plus   
15    192852         Veeru            3                    iPhone 9   
16    192853       Lavanya           16                   iPhone 7s   
17    192854   Mallikarjun           13                   LG Mobile   
18    192855         Vijay            9      Samsung Galaxy S9 Plus   
19    192856       Karteek            4                    iPhone 8   
20    192857         Mohan           24          Macbook Pro Laptop   
21    192858          Venu           23  Bose SoundSport Headphones   
22    192859     Madhurima            7          LG Washing Machine   
23    192860         Venki           15                    iPhone 8   
24    192861         Veeru            3          Samsung Galaxy S20   
25    192862    Nireekshan            1               Flatscreen TV   
26    192863        Daniel            6                    iPhone 8   
27    192864         Kedar            2                Google Phone   
28    192865     Madhurima            7      LG ThinQ Refrigerator    
29    192866       Karteek            4                    iPhone 8   

    Product cost  Quantity  
0          65999         1  
1          63000         2  
2          75999         1  
3          60000         2  
4          69999         3  
5          65999         2  
6          55999         3  
7          55999         3  
8          55999         2  
9          63000         1  
10         63000         1  
11         63999         2  
12         65999         2  
13         60000         2  
14         69999         1  
15         60000         2  
16         55000         1  
17         65999         1  
18         69000         2  
19         65000         2  
20         59000         1  
21         63000         1  
22         69000         1  
23         60000         1  
24         51999         2  
25         75999         2  
26         69000         1  
27         60000         1  
28         61000         1  
29         50000         2

In [83]:
df.drop([1,10,15],axis=0,inplace=True)
df

Order Id Customer name  Customer Id                Product name  \
0     192837         Veeru            3                   LG Mobile   
2     192839        Balaji           12      34in Ultrawide Monitor   
3     192840        Shahid           20                   iPhone 11   
4     192841         Vinay           10  Bose SoundSport Headphones   
5     192842         Vinay           10                20in Monitor   
6     192843        Balaji           12                    iPhone 8   
7     192844    Nireekshan            1      27in 4K Gaming Monitor   
8     192845          Venu           23                    iPhone 9   
9     192846         Veeru            3                20in Monitor   
11    192848         Kedar            2               Flatscreen TV   
12    192849          Venu           23          Samsung Galaxy S20   
13    192850       Neelima           19             ThinkPad Laptop   
14    192851        Daniel            6      Samsung Galaxy S9 Plus   
16    192853       Lavanya           16                   iPhone 7s   
17    192854   Mallikarjun           13                   LG Mobile   
18    192855         Vijay            9      Samsung Galaxy S9 Plus   
19    192856       Karteek            4                    iPhone 8   
20    192857         Mohan           24          Macbook Pro Laptop   
21    192858          Venu           23  Bose SoundSport Headphones   
22    192859     Madhurima            7          LG Washing Machine   
23    192860         Venki           15                    iPhone 8   
24    192861         Veeru            3          Samsung Galaxy S20   
25    192862    Nireekshan            1               Flatscreen TV   
26    192863        Daniel            6                    iPhone 8   
27    192864         Kedar            2                Google Phone   
28    192865     Madhurima            7      LG ThinQ Refrigerator    
29    192866       Karteek            4                    iPhone 8   

    Product cost  Quantity  
0          65999         1  
2          75999         1  
3          60000         2  
4          69999         3  
5          65999         2  
6          55999         3  
7          55999         3  
8          55999         2  
9          63000         1  
11         63999         2  
12         65999         2  
13         60000         2  
14         69999         1  
16         55000         1  
17         65999         1  
18         69000         2  
19         65000         2  
20         59000         1  
21         63000         1  
22         69000         1  
23         60000         1  
24         51999         2  
25         75999         2  
26         69000         1  
27         60000         1  
28         61000         1  
29         50000         2

In [84]:
df.reset_index(drop=True)

Order Id Customer name  Customer Id                Product name  \
0     192837         Veeru            3                   LG Mobile   
1     192839        Balaji           12      34in Ultrawide Monitor   
2     192840        Shahid           20                   iPhone 11   
3     192841         Vinay           10  Bose SoundSport Headphones   
4     192842         Vinay           10                20in Monitor   
5     192843        Balaji           12                    iPhone 8   
6     192844    Nireekshan            1      27in 4K Gaming Monitor   
7     192845          Venu           23                    iPhone 9   
8     192846         Veeru            3                20in Monitor   
9     192848         Kedar            2               Flatscreen TV   
10    192849          Venu           23          Samsung Galaxy S20   
11    192850       Neelima           19             ThinkPad Laptop   
12    192851        Daniel            6      Samsung Galaxy S9 Plus   
13    192853       Lavanya           16                   iPhone 7s   
14    192854   Mallikarjun           13                   LG Mobile   
15    192855         Vijay            9      Samsung Galaxy S9 Plus   
16    192856       Karteek            4                    iPhone 8   
17    192857         Mohan           24          Macbook Pro Laptop   
18    192858          Venu           23  Bose SoundSport Headphones   
19    192859     Madhurima            7          LG Washing Machine   
20    192860         Venki           15                    iPhone 8   
21    192861         Veeru            3          Samsung Galaxy S20   
22    192862    Nireekshan            1               Flatscreen TV   
23    192863        Daniel            6                    iPhone 8   
24    192864         Kedar            2                Google Phone   
25    192865     Madhurima            7      LG ThinQ Refrigerator    
26    192866       Karteek            4                    iPhone 8   

    Product cost  Quantity  
0          65999         1  
1          75999         1  
2          60000         2  
3          69999         3  
4          65999         2  
5          55999         3  
6          55999         3  
7          55999         2  
8          63000         1  
9          63999         2  
10         65999         2  
11         60000         2  
12         69999         1  
13         55000         1  
14         65999         1  
15         69000         2  
16         65000         2  
17         59000         1  
18         63000         1  
19         69000         1  
20         60000         1  
21         51999         2  
22         75999         2  
23         69000         1  
24         60000         1  
25         61000         1  
26         50000         2